/**
 * PreloadScene — loads all assets needed before GameScene starts.
 *
 * Two-pass load strategy required by Phaser 3:
 *   Pass 1 (preload)  → tiny JSON files: map data + optional imageMap
 *   Pass 2 (create)   → tile PNGs + critter PNG derived from pass-1 data
 *
 * Asset paths (public/ is served at root):
 *   Tiles:   assets/tiles/{tileName}.png
 *   Critters: assets/critters/{name}.png
 *   imageMap: assets/art/imageMap.json  (written by scripts/frm_to_png.py)
 *
 * Fallback policy:
 *   Any file that returns a 404 triggers the Phaser 'loaderror' event.
 *   We catch it, warn to console, and leave the texture slot empty.
 *   IsoRenderer.ensureTileTextures() then generates a procedural diamond
 *   for that key — so the game always renders something visible.
 */

import Phaser from 'phaser'

// ── Asset base paths ───────────────────────────────────────────────────────
const TILE_BASE     = 'assets/tiles/'
const CRITTER_BASE  = 'assets/critters/'
const IMAGE_MAP_URL = 'assets/art/imageMap.json'

/**
 * Fallout 1 hero-male critter base name (no-armour standing animation).
 * frm_to_png.py strips the extension from critters.lst, so the PNG is
 * stored as <base>.png — one horizontal sprite sheet of all frames.
 * "hmjmpsna" = Hero Male Jump Standing No Armour (FO1 standard player art).
 */
const PLAYER_CRITTER_NAME = 'hmjmpsna'

/** Phaser texture key used everywhere for the player critter. */
export const PLAYER_TEXTURE_KEY = 'player_critter'

export class PreloadScene extends Phaser.Scene {
  // Retained between passes so create() can read them
  private imageMap: Record<string, unknown> = {}

  constructor() {
    super({ key: 'PreloadScene' })
  }

  // ── Pass 1: load JSON ────────────────────────────────────────────────────

  preload(): void {
    this.buildProgressUI()

    // Map JSON (always present — committed to git)
    this.load.json('v13ent', 'assets/maps/v13ent.json')

    // imageMap.json is generated by scripts/frm_to_png.py.
    // It may not exist yet if the pipeline hasn't been run locally.
    // Phaser treats a 404 as a non-fatal load error — we just get null back.
    this.load.json('imageMap', IMAGE_MAP_URL)
  }

  // ── Pass 2: load PNGs derived from pass-1 JSON ──────────────────────────

  create(): void {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const mapData: any  = this.cache.json.get('v13ent')
    this.imageMap        = (this.cache.json.get('imageMap') as Record<string, unknown>) ?? {}

    // Collect all unique tile names referenced by the floor map
    const tileNames = new Set<string>()
    const floor: string[][] = mapData?.levels?.[0]?.tiles?.floor ?? []
    for (const row of floor) {
      for (const name of row) {
        if (name && name !== 'grid000') tileNames.add(name)
      }
    }

    // Warn instead of crashing for missing PNGs
    this.load.on('loaderror', (file: Phaser.Loader.File) => {
      console.warn(`[PreloadScene] Asset not found (will use placeholder): ${file.url}`)
    })

    // ── Tile PNGs ──
    // Key = tile name (e.g. "metal01") — IsoRenderer.ensureTileTextures()
    // checks textures.exists(name) and skips diamond generation if found.
    for (const name of tileNames) {
      this.load.image(name, `${TILE_BASE}${name}.png`)
    }

    // ── Player critter ──
    // Load as spritesheet when frame dimensions are known (imageMap present),
    // else fall back to a plain image (shows full animation strip).
    const critterKey = `art/critters/${PLAYER_CRITTER_NAME}`
    const critterInfo = this.imageMap[critterKey] as { frameWidth?: number; frameHeight?: number } | undefined

    if (critterInfo?.frameWidth && critterInfo?.frameHeight) {
      this.load.spritesheet(PLAYER_TEXTURE_KEY, `${CRITTER_BASE}${PLAYER_CRITTER_NAME}.png`, {
        frameWidth:  critterInfo.frameWidth,
        frameHeight: critterInfo.frameHeight,
      })
    } else {
      this.load.image(PLAYER_TEXTURE_KEY, `${CRITTER_BASE}${PLAYER_CRITTER_NAME}.png`)
    }

    // Pass data to GameScene then hand off once load completes
    this.load.once('complete', () => {
      this.scene.start('GameScene', {
        mapData:  mapData,
        imageMap: this.imageMap,
      })
    })

    // Kick off pass-2 loading.
    // If the queue happens to be empty (no tiles, no critter) this fires
    // 'complete' synchronously on the next frame — GameScene still starts.
    this.load.start()
  }

  // ── Loading bar UI ───────────────────────────────────────────────────────

  private buildProgressUI(): void {
    const { width, height } = this.scale
    const cx = width  / 2
    const cy = height / 2
    const barW = 360
    const barH = 14

    this.add.text(cx, cy - 36, 'VAULT 13', {
      fontFamily: 'monospace',
      fontSize:   '22px',
      color:      '#c8a84b',
    }).setOrigin(0.5)

    this.add.text(cx, cy - 14, 'loading…', {
      fontFamily: 'monospace',
      fontSize:   '11px',
      color:      '#887755',
    }).setOrigin(0.5)

    // Track background
    this.add.rectangle(cx, cy + 14, barW + 4, barH + 4, 0x1a1008)
    this.add.rectangle(cx, cy + 14, barW + 2, barH + 2, 0x4a3810)

    const bar = this.add.rectangle(cx - barW / 2, cy + 14, 0, barH, 0xc8a84b).setOrigin(0, 0.5)
    this.load.on('progress', (v: number) => { bar.width = barW * v })
  }
}
